version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "80:80"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONPATH=/app
    command: uvicorn main:app --host 0.0.0.0 --port 80  # اینجا می‌خوایم سرور بک‌اند رو اجرا کنیم

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: serve -s build  # اینجا می‌خوایم سرور فرانت‌اند رو اجرا کنیم
